### ISSUE TITLE
Consistent (relative to tea/cli) User-Agent for requests

### ISSUE THREAD

**Issue by mxcl** [teaxyz/gui#273]
Check the tea/cli code for this and use the same format.

**Comment by getneil** [comment]
might be better to finish libtea integration first, since UserAgent value is now "tea.lib/version"

**Comment by mxcl** [comment]
To change the UserAgent call `useConfig` at the app’s initialization.

You'll also want to ensure the right prefix is set since useConfig determines it from the value of TEA_PREFIX but `.app`s on macOS do not get the env via an evaluated shell so you’ll want to shell out to `tea --prefix` like you do currently.

though that's not ideal since it'll be slow, probs `sh -c 'echo $TEA_PREFIX'` would be much faster.
