### ISSUE TITLE
releases should be proper github releases

### ISSUE THREAD

**Issue by mxcl** [teaxyz/gui#496]
It is not enough to just tag the release.

**Comment by getneil** [comment]
this has been partially implemented already by jacob's xc script, lacking is attaching of installer to the release info. any chance we can get away with just adding the link of the installer to the release description?

**Comment by mxcl** [comment]
> any chance we can get away with just adding the link of the installer to the release description?

why stop there? Why not not even post the dmg at all and just provide a llm generated description of what the app is like?
