### ISSUE TITLE
librify tea/cli and use it

### ISSUE THREAD

**Issue by mxcl** [teaxyz/gui#533]
I will librify, but first we need to discuss how we will use it.

I don’t particularly want to publish to npm straight away. GitHub packages will work right?

Then we can use libtea in all places and work towards our primitives future we promised.

**Comment by getneil** [comment]
@ABevier i added it but used only to set user-agent atm.

**Comment by owenjames** [comment]
note: new progress meter for the whole operation available, 0.0-1.0

**Comment by getneil** [comment]
this is done.
