### ISSUE TITLE
Ensure `.dmg` is codesigned and the notarization is stapled

### ISSUE THREAD

**Issue by mxcl** [teaxyz/gui#547]
This isn't urgent, but it's polish we should eventually apply.

I don’t think we can do this with the electron-build system, but I may be wrong. If we can't then the `notarytool` that Apple provide will make this easy.

**Comment by getneil** [comment]
this has been implemented partially in dev builds:

- dev uses notary tool
- and stapled

todo: dmg output doesnt look nice ui wise.

**Comment by getneil** [comment]
this is done. latest `@electron/notarize` is using notarytool and stapling it pre-dmg build in the electron-builder
