### ISSUE TITLE
respect tea --prefix if tea/cli exists

### ISSUE THREAD

**Issue by razvanazamfirei** [teaxyz/gui#569]
tea/gui uses `$HOME/.tea` without the option to modify it. If tea/cli was installed with `sh <(curl https://tea.xyz) --prefix $RAND_DIR/tea` and tea/gui is installed on top, users will have 2 separate tea directories, `$HOME/.tea` and `$RAND_DIR/tea`. 

tea/gui should defer to `tea --prefix` if it exists.

**Comment by getneil** [comment]
good catch.
