### ISSUE TITLE
Auto-GPT not installing and not running when "installed"

### ISSUE THREAD

**Issue by clickbrain** [teaxyz/gui#628]
I am having an issue with Auto-GPT not installing or not showing that it has been installed in the UI, because Install button doesn't change to Uninstall and there is no Open In Terminal button. 

When I did have it installed, it would not open and run. Getting a message in CLI showing package inventory and a Tea prompt. 

See attached screen recording. 

https://github.com/teaxyz/cli/assets/963889/899f7ce5-22d7-4317-9c6b-96f40dde107e

**Comment by mxcl** [comment]
@clickbrain I believe ⌘R will fix it

**Comment by mxcl** [comment]
does typing `auto-gpt` not work?

I agree it should run that for you but we're working towards that.

**Comment by clickbrain** [comment]
Duh... I guess I could have tried that. It does initiate when I enter auto-gpt at the tea prompt. Didn't even think to try it. 

Future suggestion - A UI element in Tea or encouragement to the projects to setup prompts for info that need to go into env variables like OpenAI keys. I know how to do it, but many users that want to play with these types of apps will have zero clue. I realize Auto-gpt is a bit of a hack job at this point and too new for these types of things, but would definitely be a boost to adoption in Tea. Could even see an aggregate env variable setup in Tea for specific app types that use APIs like ChatGPT, or Pinecone or whatever and then those get passed to the apps.

**Comment by mxcl** [comment]
yeah totally want to have integrations to set up environment. Haven't figured out how it will work yet. But was also thinking about `OPENAI_API_KEY` and hugging-face-cli login and that.

What we package will always be a “hack job” but we can make it feel like that doesn't matter because it all just works. That's my goal.

> One more thing. A button in Tea that opens the folder in Finder for the app you are in so inexperienced users can find what they need to edit more easily.

Added to the list! Thanks.
