### ISSUE TITLE
Update tea application install visual with an obvious drag to applications design

### ISSUE THREAD

**Issue by owenjames** [teaxyz/gui#629]

**Comment by tsmitty11** [comment]
![installer-background](https://github.com/teaxyz/gui/assets/49042513/0adc210e-1d14-4475-9c5c-5f127b233786)

**Comment by tsmitty11** [comment]
[tea-design-installer-v2.pdf](https://github.com/teaxyz/gui/files/11581462/tea-design-installer-v2.pdf)
