### ISSUE TITLE
Detect if cli magic is enabled and warn if not, with a button to enable

### ISSUE THREAD

**Issue by owenjames** [teaxyz/gui#642]
- Determine optimal logic to detect cli magic
- Create UI for warning (modal) and the button to enable magic

**Comment by tsmitty11** [comment]
@owenjames @getneil Should this be something that is permanently accessible? I.e. the modal says the bit about magic not being enables, but also informs the user that they can toggle magic at any point via settings (for example)?

**Comment by tsmitty11** [comment]
A couple of different options for notifying about magic:

https://www.loom.com/share/1284f5d77d0043388b216c0c938f97f9

**Comment by tsmitty11** [comment]
A universal notifcication in the form of a tob banner ribbon: 
<img width="998" alt="Screen Shot 2023-06-07 at 12 12 35 AM" src="https://github.com/teaxyz/gui/assets/49042513/f9399e7e-d0b9-4c9d-823c-1dabb90a927e">

**Comment by tsmitty11** [comment]
And a more localized solution in the event that opening in terminal is the only event that would necessitate magic
<img width="958" alt="Screen Shot 2023-06-07 at 12 14 06 AM" src="https://github.com/teaxyz/gui/assets/49042513/02735a15-60b8-45f3-8480-2a009034a1db">

**Comment by getneil** [comment]
@tsmitty11 we dont have the ability to detect whether magic required for a package to open. So we probably can go with the banner and settings(switch)?

**Comment by tsmitty11** [comment]
@getneil yeah let's go with the banner and their respective states. Here's a mockup of what the magic toggle would look like in the settings dropdown.
<img width="467" alt="Screen Shot 2023-06-07 at 1 32 06 PM" src="https://github.com/teaxyz/gui/assets/49042513/17c9ce7a-7362-485b-9bbf-d8b969ec5da2">

**Comment by tsmitty11** [comment]
@getneil here's the screenshot with the toggle states as well. I think it would be cool to have the color smoothly transition from that gray to purple on toggle.

<img width="200" alt="Screen Shot 2023-06-07 at 3 11 59 PM" src="https://github.com/teaxyz/gui/assets/49042513/3bc49be2-bc2d-4da2-934a-a5f4ddd1d3e8">

**Comment by getneil** [comment]
this is not happening for now.
