### ISSUE TITLE
multiple language support

### ISSUE THREAD

**Issue by owenjames** [teaxyz/gui#671]
- Add dropdown selection for language
- Find any remaining areas that aren't translatable and convert them
- Use translation file for text

**Comment by tsmitty11** [comment]
Here's a mockup of the language dropdown with a 'contribute' option at the bottom. That would link to the relevant docs for adding languages. Octocat/GitHub icon can be called with `class="icon-github"`

Screenshot:
<img width="396" alt="Screen Shot 2023-06-16 at 7 41 30 PM" src="https://github.com/teaxyz/gui/assets/49042513/a1aadc26-333c-4bae-a5ba-0d811da5e091">

**Comment by getneil** [comment]
this is done
