### ISSUE TITLE
gpt4all not running when click open button

### ISSUE THREAD

**Issue by clickbrain** [teaxyz/gui#678]
GPT4All will run if you type gpt4all at the Tea prompt, but does not startup when you hit the Open button in the Tea Gui. It just opens to the Tea prompt. 

This happened with auto-gpt as well and just wanted you to be aware that the command isn't being run after clicking Open in the GUI.

**Comment by clickbrain** [comment]
On another note, when I run gpt4all at the prompt, it only runs the CLI version of the application, but the screens and descriptions are for the web-based version.

**Comment by getneil** [comment]
@clickbrain thanks for reporting this we will take a look

**Comment by mxcl** [comment]
gpt4all has no entrypoint as yet. Easy enough to add. pkgs without entrypoints only open a terminal with the pkg env loaded
