### ISSUE TITLE
Tea update causes a crash

### ISSUE THREAD

**Issue by clickbrain** [teaxyz/gui#695]
Saw the indicator at the top of the UI
Choose the drop down
Choose update
Tea crashes

Screen recording - https://github.com/teaxyz/gui/assets/963889/d32fb3fe-4b75-464d-aca8-e35b34588caa

**Comment by clickbrain** [comment]
This is strange, maybe it wasn't a crash. Gave no indicator of anything when it closed, but then did restart and now showing up to date. So maybe it is not crashing, but just starting update process. May want to tell the user, because it just looks like it is crashing.

**Comment by owenjames** [comment]
Yes, thank you for the recording, it should tell the user something to not look like a crash

**Comment by getneil** [comment]
<img width="1029" alt="Screenshot 2023-07-03 at 1 13 53 PM" src="https://github.com/teaxyz/gui/assets/7913978/8ee4d56c-9f3e-4fcf-b304-d4297aec49dc">

Here is a mock proposal and there is a pr also. @clickbrain @owenjames

**Comment by tsmitty11** [comment]
@getneil I think this is a good aspect for managing expectations. Let's also: 

1. Include a confirmation modal after the user clicks 'update' that includes some microcopy informing them about the update process and gives them 'restart' or 'cancel' options. 

2. Assuming that proceed with the update, let's have a progress indicator in the top ribbon. 

3. Once that's complete, we can have a notification telling them that the app needs to restart.

4. After restarting, we can have a notification up top informing them that gui has been updated to Version x.x.x 

I'll provide some Figma designs today.

**Comment by tsmitty11** [comment]
@getneil @owenjames here's a Loom video of a Figma prototype:

https://www.loom.com/share/79a860ed0a7241b5b17b6f8a61a2db43?sid=d8de2004-6101-42d9-a776-137cac895cfd

And here's a link to the Figma prototype itself:

https://www.figma.com/proto/UZJ2CrxsoX0pkhEY4NZE5j/GUI-Master?page-id=10%3A372&type=design&node-id=142-898&viewport=-1100%2C-4714%2C0.81&scaling=min-zoom&starting-point-node-id=117%3A4639&mode=design&t=htR4KAOyzdj65Aoq-1

And here's the link to the art boards in Figma if you need to poke around: 

https://www.figma.com/file/UZJ2CrxsoX0pkhEY4NZE5j/GUI-Master?type=design&node-id=142%3A898&mode=design&t=gOvTb47rQ0B0DUTv-1

**Comment by getneil** [comment]
@tsmitty11 the updating spinner will not happen because the update button is clickable it means the installer has already been downloaded. we can go directly to the countdown

**Comment by tsmitty11** [comment]
@getneil okay that works! So straight from confirm modal to countdown.

**Comment by mxcl** [comment]
adding a confirm for an action the user explicitly asked is wrong.

From now on I need to approve all ui pls.

And remove the confirm and the countdown.
