### ISSUE TITLE
Wrong image usage

### ISSUE THREAD

**Issue by owenjames** [teaxyz/gui#706]
![image](https://github.com/teaxyz/gui/assets/5668195/525d7a17-415c-4d8d-88f2-98973e3296f6)
There appears to be an issue with re-using images while rendering package grids
Likely related to latency or missing images, but image "carry-overs" during rendering iterations should be prevented
If this is deep into the svelte rendering, consider adding post-render validation

**Comment by getneil** [comment]
seems to be not an issue anymore.

**Comment by owenjames** [comment]
still having this issue in the update view, when clicking update all
