### ISSUE TITLE
Discover Page with Local AI Section + Screenshots on Details Page

### ISSUE THREAD

**Issue by tsmitty11** [teaxyz/gui#761]
## Overview:

As per thread in #design channel on Slack, this is a redesign of the discover page to feature a section for Local AI. As follows, it's a full-width spotlight banner, a click-able, horizontal scroll section for the AI packages, and then a dump of recent package cards below. Design has been approved by @mxcl [on Slack](https://teaxyz.slack.com/archives/C031VR5EVSN/p1690302582620319). 

On the package details page, we should have a carousel of package screenshots. The screenshot should appear only for the 'not yet installed' state. Once the package has been installed, the screenshots can disappear.

## Discover Page:

**Image Preview:**
<img width="800" alt="Screen Shot 2023-07-31 at 6 16 03 PM" src="https://github.com/teaxyz/gui/assets/49042513/9c2de505-f10f-43ff-8e89-13245af5dbdb">

**Loom preview:**
https://www.loom.com/share/53c1fa456dae4e8fb011c1b49a35a323?sid=660c7fd3-0285-4241-ad8d-549be637841a

**Figma art board:**
https://www.figma.com/file/UZJ2CrxsoX0pkhEY4NZE5j/GUI-Master?type=design&node-id=771%3A3768&mode=dev

## Package Details Page:

_Screenshots/Not Installed Yet:_

**Image Preview:**
<img width="800" alt="Screen Shot 2023-08-01 at 11 34 44 AM" src="https://github.com/teaxyz/gui/assets/49042513/653d8912-0b71-4d86-960f-e40f3da4f0f9">

Figma art board:
https://www.figma.com/file/UZJ2CrxsoX0pkhEY4NZE5j/GUI-Master?type=design&node-id=866%3A6934&mode=dev

_No Screenshots/Installed_

**Image Preview:**
<img width="800" alt="Screen Shot 2023-08-01 at 11 35 08 AM" src="https://github.com/teaxyz/gui/assets/49042513/2d6c6a78-f4ef-402b-b87b-2abcad86c358">

**Figma art board:**
https://www.figma.com/proto/UZJ2CrxsoX0pkhEY4NZE5j/GUI-Master?page-id=10%3A372&node-id=573-3666&scaling=min-zoom&starting-point-node-id=117%3A4639&mode=design&t=IDYxpWuCZGi5nfTE-1

**Comment by getneil** [comment]
@tsmitty11 what does `view all` look like?

**Comment by tsmitty11** [comment]
@getneil A filtered category page just like 'installed' and 'updates available' . @mxcl can weigh in on whether it's necessary.

**Comment by mxcl** [comment]
drop the view all for now.

**Comment by getneil** [comment]
@tsmitty11 can we get the copy for the sub-description for the `local AI essentials`
